dist: bionic
sudo: required
language:
  - cpp
python: "3.7"
addons:
  apt:
    sources:
    - llvm-toolchain-bionic-9
    - ubuntu-toolchain-r-test
    packages:
    - clang-7
    - cmake
    - gcc-8
    - g++-8
    - ninja-build
  homebrew:
    packages:
    - cmake
    - gcc@8
    - ninja

matrix:
  include:
    - os: linux
      compiler: g++
      env: PATH=$HOME/.local/bin:$PATH
    - os: linux
      compiler: clang
      env: PATH=$HOME/.local/bin:$PATH
    - os: osx
      compiler: clang
      env: PATH=$HOME/.local/bin:$PATH
    - os: windows
      compiler: g++
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
	- choco install python
    - os: windows
      compiler: clang
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python
install:
  - python -m pip install --upgrade pip
  - pip install conan
  - conan user
  - mkdir build
  - cd build
  - conan install .. --build missing
  - cd ..
script:
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email: false