dist: bionic
sudo: required
language:
  - cpp
python: "3.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-8
      - clang-6.0
      - cmake

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
      install:
        - gcc --version
    - os: osx
      compiler: clang
    - os: windows
      compiler: gcc
      install:
        - echo test
    - os: windows
      compiler: clang
      install:
        - echo test


install:
  - sudo pip install conan
  - conan user
script:
  - conan install . --build missing
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email: false
