dist: bionic
sudo: required
language:
  - cpp
python: "3.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-8
      - clang-6.0
      - cmake

matrix:
  include:
    - os: linux
      compiler: g++
    - os: linux
      compiler: clang
    - os: osx
      compiler: g++
    - os: osx
      compiler: clang
    - os: windows
      compiler: g++
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install:
        - choco install python
        - python -m pip install --upgrade pip
        - pip install conan
        - conan user
        - conan install . --build missing
    - os: windows
      compiler: clang
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install:
        - choco install python
        - python -m pip install --upgrade pip
        - pip install conan
        - conan user
        - conan install . --build missing


install:
  - sudo pip install conan
  - conan user
  - conan install . --build missing
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email: false
