dist: bionic
sudo: required
language:
  - cpp
os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script: make
notifications:
  email: false