dist: bionic
sudo: required
language:
  - cpp
python: "3.8"
addons:
  apt:
    sources:
    - llvm-toolchain-bionic-9
    - ubuntu-toolchain-r-test
    packages:
    - clang-7
    - cmake
    - gcc-8
    - g++-8
    - ninja-build
  homebrew:
    packages:
    - cmake
    - gcc@8
    - ninja

matrix:
  include:
    - os: linux
      compiler: g++
    - os: linux
      compiler: clang
    # - os: osx
    #   compiler: g++
    - os: osx
      compiler: clang
    - os: windows
      compiler: g++
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - choco install python
        - python -m pip install --upgrade pip
        - pip install conan
        - conan user
        - conan install . --build missing
    - os: windows
      compiler: clang
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - choco install python
        - python -m pip install --upgrade pip
        - pip install conan
        - conan user
        - conan install . --build missing


install:
  - sudo pip install conan
  - conan user
  - conan install . --build missing
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email: false
