dist: bionic
sudo: required
language:
  - cpp
python: "3.7"
os:
  - linux
  - windows
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-8
      - clang-6.0
      - cmake
install:
  - sudo pip install conan
  - conan user
  - conan --build glew
script:
  - conan install .
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email: false